<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-09-03T13:39:13Z" name="Suite" finished-at="2019-09-03T13:39:41Z" duration-ms="27929">
    <groups>
    </groups>
    <test started-at="2019-09-03T13:39:13Z" name="Test" finished-at="2019-09-03T13:39:41Z" duration-ms="27929">
      <class name="org.atmecs.utils.flight_ticket.Pricechoosen">
        <test-method signature="price()[pri:1, instance:org.atmecs.utils.flight_ticket.Pricechoosen@2893de87]" started-at="2019-09-03T19:09:41Z" name="price" finished-at="2019-09-03T19:09:41Z" duration-ms="4" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.atmecs.utils.flight_ticket.Pricechoosen.price(Pricechoosen.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- price -->
      </class> <!-- org.atmecs.utils.flight_ticket.Pricechoosen -->
      <class name="org.atmecs.utils.flight_ticket.AppTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:org.atmecs.utils.flight_ticket.AppTest@20d3d15a]" started-at="2019-09-03T19:09:06Z" name="setup" finished-at="2019-09-03T19:09:13Z" duration-ms="6881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="flightticket()[pri:0, instance:org.atmecs.utils.flight_ticket.AppTest@20d3d15a]" started-at="2019-09-03T19:09:13Z" name="flightticket" finished-at="2019-09-03T19:09:41Z" duration-ms="27873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightticket -->
        <test-method signature="testApp()[pri:0, instance:org.atmecs.utils.flight_ticket.AppTest@20d3d15a]" started-at="2019-09-03T19:09:41Z" name="testApp" finished-at="2019-09-03T19:09:41Z" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp -->
      </class> <!-- org.atmecs.utils.flight_ticket.AppTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
